name: Deploy React App to AWS S3 (Master)

on:
  push:
    branches:
      - master  # Se ejecuta solo cuando haces push a master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Instalar dependencias
      run: pnpm install

    - name: Construir el proyecto
      run: pnpm run build

    - name: Desplegar en S3
      run: aws s3 sync dist/ s3://eduardo-aws --delete --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
